Add initial deploy image
  - Add deploy image building stages to Dockerfile
    NOTE: This moves machine building into this Dockerfile
  - Refactor docker compose framework to support
    both deploy and dev environment images
  - Add running E2E tests to docker compose
    framework
  - Add entrypoint.sh (server) startup file
    used as CMD in deploy image
  - Add app_is_ready.rb healthcheck script
  - Add deploy image building, pusghing and
    vetting to workflows

diff --git a/script/dockercomposerun b/script/dockercomposerun
--- a/script/dockercomposerun
+++ b/script/dockercomposerun
@@ -1,19 +1,23 @@
 #!/bin/sh
+# ----------------------------------------------------------------------
 # This script runs the project docker-compose framework.
 #
-# NOTE: Currently, only the development environment is supported
-#
-# - The arguments to this script are passed to the APP service
+# - The arguments to this script are passed to the app service
 #   as command override
 #
 # - Any environment variables set when calling this script are passed
 #   through to the docker-compose framework
 #   (e.g. configuration other than the defaults)
 #
+# OPTIONS:
+# -c: Use the docker-compose CI environment with APP_IMAGE
+# -d: Use the docker-compose Dev environment with APP_IMAGE
+# -n: No application database in the docker-compose environment
+# -t: Run the e2e tests (and not the app service)
 # ----------------------------------------------------------------------
 
 usage() {
-  echo "Usage: $0 [CMD]"
+  echo "Usage: $0 [-cdnt] [CMD]"
 }
 
 err_exit() {
@@ -27,16 +31,71 @@ err_exit() {
 # Exit script on any errors
 set -e
 
-echo 'DOCKER VERSIONS...'
-docker --version
-docker-compose --version
+# Handle options
+while getopts ":cdnt" options; do
+  case "${options}" in
+    c)
+      echo "CI Environment"
+      ci=true
+      ;;
+
+    d)
+      echo "Development Environment"
+      devenv=true
+      ;;
+
+    n)
+      echo "No Database"
+      no_database=true
+      ;;
+
+    t)
+      echo "Running End-To-End (E2E) Tests"
+      run_e2etests=true
+      ;;
+
+    \?)
+    err_exit "Invalid Option: -$OPTARG" 1
+      ;;
+  esac
+done
+shift $((OPTIND-1))
+
+echo ''
+echo "ENVIRONMENT VARIABLES..."
+env
 echo ''
 
-echo 'DOCKER-COMPOSE COMMAND...'
-docker_compose_command='docker-compose -f docker-compose.yml '
+echo 'DOCKER (COMPOSE) VERSION...'
+docker --version
+echo ''
 
-echo "...Using Development Environment with APP_IMAGE:[${APP_IMAGE}]"
-docker_compose_command="${docker_compose_command} -f docker-compose.dev.yml "
+# Override docker compose environments
+echo 'DOCKER-COMPOSE COMMAND...'
+docker_compose_command='docker compose -f docker-compose.yml '
+
+# Unless the no database option is set, add the database service
+if [ -z ${no_database} ]; then
+  echo "...Adding Database to Environment"
+  docker_compose_command="${docker_compose_command} -f docker-compose.db.yml "
+fi
+
+if [ ! -z ${ci} ]; then
+  echo "...Using CI Environment with Image [${APP_IMAGE}]"
+  docker_compose_command="${docker_compose_command} -f docker-compose.ci.yml "
+fi
+
+if [ ! -z ${devenv} ]; then
+  echo "...Using Development Environment with Image [${APP_IMAGE}]"
+  docker_compose_command="${docker_compose_command} -f docker-compose.dev.yml "
+fi
+echo "...COMMAND: [${docker_compose_command}]"
+echo ''
+
+if [ ! -z ${run_e2etests} ]; then
+  echo "...Running E2E Tests Image [${E2ETESTS_IMAGE}] against Image [${APP_IMAGE}]"
+  docker_compose_command="${docker_compose_command} -f docker-compose.e2e.yml "
+fi
 
 echo 'DOCKER-COMPOSE CONFIGURATION...'
 $docker_compose_command config
@@ -56,19 +115,26 @@ echo ''
 echo "DOCKER-COMPOSE RUNNING [$@]..."
 # Allow to fail but catch return code
 set +e
-# Specify the --service-ports option to expose app's PORTS
-# on host machine (by default docker-compose run does not
-# expose host ports)
-$docker_compose_command run --rm --service-ports app "$@"
-run_return_code=$?
-# NOTE return code must be caught before any other command
+if [ -z ${run_e2etests} ]; then
+  # Specify the --service-ports option to expose app's PORTS
+  # on host machine (by default docker-compose run does not
+  # expose host ports)
+  $docker_compose_command run --rm --service-ports app "$@"
+  # NOTE return code must be caught before any other command
+  run_return_code=$?
+else
+  echo "RUNNING THE E2E TESTS (e2etests SERVICE) (NOT app SERVICE)..."
+  $docker_compose_command run --rm e2etests "$@"
+  # NOTE return code must be caught before any other command
+  run_return_code=$?
+fi
 set -e
 echo ''
 
 if [ $run_return_code -eq 0 ]; then
-    run_disposition='PASSED'
+  run_disposition='PASSED'
 else
-    run_disposition='FAILED'
+  run_disposition='FAILED'
 fi
 echo "...RUN [${run_disposition}] WITH RETURN CODE [${run_return_code}]"
 echo ''
